# configure frontend for deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-frontend-deployment
  namespace: to-do-app
spec:
  replicas: 2
  selectors:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      name: to-do-app-frontend
      labels:
        app: to-do-app
    spec:
      containers:
        - name: frontend-container
          image: to-do-app-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URL
              value: "mongo://mongo-service:2701/to-dos"
